# Generated by Django 5.0.6 on 2024-05-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='due',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
